@startuml
skinparam BackgroundColor transparent

state Cliente
state Venta
state Cita
state Reservación
state Vendedor
state Recepcionista
state Caja
state Producto
state Entrega
state Capacitación
state "Servicio\nProfesional" as servicio
state "Maquillista\ \nEstilista" as Especialista

Cliente --> Vendedor : Es atendido por
Cliente --> Recepcionista : Es atendido por
Cliente <-- Especialista
Cliente --> Especialista

Vendedor --> Venta : Lleva la
Vendedor --> Caja : Registra en la
Vendedor --> Entrega: Manda la

Entrega --> Producto  : Lleva los
Venta --> Producto : Contiene

Recepcionista -left-> Cita : Gestiona
Recepcionista --> Reservación : Gestiona
Recepcionista --> Caja : Registra en la

Especialista -right-> Cita
Especialista --> Reservación

Especialista --> servicio : Aplica
Especialista --> Capacitación : Imparte
@enduml