@startuml
skinparam BackgroundColor transparent

state Cliente
state Venta
state Cita
state Reservación
state Vendedor
state Recepcionista
state Caja
state Producto
state Entrega
state Capacitación
state "Servicio\nProfesional" as servicio
state "Maqullista\ \nEstilista" as Especialista

Cliente --> Vendedor : Es atendido por
Cliente --> Recepcionista : Es atendido por

Vendedor --> Venta : Lleva la
Vendedor --> Caja : Registra en la
Vendedor --> Entrega: Manda el

Entrega -right-> Venta : Contiene
Venta --> Producto : Contiene

Recepcionista --> Cita : Gestiona
Recepcionista --> Reservación : Gestiona
Recepcionista --> Caja

Cita --> Especialista : Atiende
Reservación --> Especialista : Atiende

Especialista -left-> servicio
Especialista -right-> Capacitación
@enduml