@startuml
skinparam BackgroundColor transparent

Cliente "1" -- "n" Venta
Venta "n" --* "1..*" Producto
Venta "1" -- "1" Delivery

class Venta
class Delivery
class Producto

Cita -- Recepcionista
Reservación -- Recepcionista

Cliente "1" -- "n" Cita
Cliente "1" -- "n" Reservación

Reservación "1..*" -- "1" Curso
Cita "1..*" -- "1" "Servicio \n Profesional "
Venta -- Vendedor

class Recepcionista
class Cita
class "Servicio \n Profesional "
class Cliente
class Reservación
class Curso
class Vendedor

@enduml