@startwbs
skinparam BackgroundColor transparent

* Fundador /\nPropietario
** Responsable\ndel Personal
*** Recepción
***< Maquillista y Estilista
*** Repartidor
** Responsable\nde Contabilidad
*** Caja
** Responsable\nde la publicidad
*** Creador de\n Contenidos

@endwb