@startuml
skinparam BackgroundColor transparent

state Initial
state Final
state S1
state S2
state S2.choice <<choice>>
state S4
state S5
state S6

state S3 {
    state exit <<exitPoint>>
    [*] -left> Entry : Recibe un pedido
    Entry -> exit
}


[*] --> Initial


Initial --> S1 : Se muestra los campos de \n los datos de venta y la opción vender
S1 -right-> S2 : Se llenan los \n datos de la venta
exit -right-> S2 : Obtiene los datos \n de una solicitid de pedido
S2 -down-> S2.choice : Se solicita vender
S2.choice -left> S4 : En local
S2.choice -> S5 : Delivery
S5 --> S6 : En espera
S6 -left-> S4 : Entrega existosamente

S4 --> Final : Guardar venta
S4 --> Final : Cancelar venta
S6 --> Final : Delivery cancelado
Final --> [*]

@enduml