@startuml
skinparam BackgroundColor transparent
title SellProducts use case state diagram

state Initial
state Final
state S1
state S2
state S2.choice <<choice>>
state S3
state S4
state S5
state S6



[*] --> Initial
[H] --> S3 : Recibe un pedido

Initial --> S1 : Se muestra los campos de \n los datos de venta y la opción vender
S1 --> S2 : Se llenan los \n datos de la venta
S3 --> S2 : Obtiene los datos \n de una solicitid de pedido
S2 --> S2.choice : Se solicita vender
S2.choice -down-> S4 : En local
S2.choice -right-> S5 : Delivery
S5 -right-> S6 : En espera
S6 --> S4 : Entrega existosamente

S4 --> Final : Guardar venta
S4 --> Final : Cancelar venta
S6 --> Final : Delivery cancelado
Final --> [*]

@enduml